name: Bug Report - Debugger
description: Create a bug report for debugging such as call stack, breakpoints, watch window, launching or attaching to a debuggee.
body:
- type: markdown
  attributes:
    value: |
      ### Is there an existing issue for this?
      Please search our [existing issues](https://github.com/microsoft/vscode-cpptools/issues) to see if an issue already exists for the bug you encountered.

      Please also review our [documentation](https://code.visualstudio.com/docs/languages/cpp) and [FAQs](https://code.visualstudio.com/docs/cpp/faq-cpp).
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide the information for the following:
        - OS and version
        - VS Code version
        - C/C++ extension version
        - OS and version of remote machine (if applicable)
        - GDB / LLDB version
    value: |
        - OS and version:
        - VS Code:
        - C/C++ extension:
        - OS and version of remote machine (if applicable):
        - GDB / LLDB version:
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug Summary and Steps to Reproduce
    description: |
      Please describe the debugging issue or debugger feature that is not working as expected.

      Include clear steps on how to reproduce the issue.
    value: |
      Bug Summary:


      Steps to reproduce:
      1. In this environment...
      2. With this config...
      3. Do '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Debugger Configurations
    description: Please provide the debugger configurations from the **tasks.json** and **launch.json** files.
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Debugger Logs
    description: |
      If applicable, please include [logging for the debugger adapter](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-debug-adapter) by adding `"logging": { "engineLogging": true, "trace": true, "traceResponse": true }` in the **launch.json** file.

      Include logs or error messages from the Debug Console or Output windows.
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Other Extensions
    description: If applicable, please list other extensions installed and if the issue persists after disabling other extensions.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Optionally provide other information that will give us more context about the issue you are encountering, such as a code sample, screenshots, or screen recording of the issue.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
