name: Bug Report - General Extension
description: Create a bug report for downloading, installing, or building the extension.
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search our [existing issues](https://github.com/microsoft/vscode-cpptools/issues) to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues.
      required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide the information for the following:
        - OS and version
        - VS Code version
        - C/C++ extension version
        - OS and version of remote machine (if applicable)
    value: |
        - OS and version:
        - VS Code:
        - C/C++ extension:
        - OS and version of remote machine (if applicable):
    render: markdown
  validations:
    required: true
- type: dropdown
  attributes:
    label: Does the issue persist after disabling any other extensions?
    options:
      - "Yes"
      - "No"
      - Not applicable, only the C/C++ extension is enabled/installed.
  validations:
    required: true
- type: textarea
  attributes:
    label: Other extensions
    description: If applicable, please list other extensions installed.
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of the issue you are encountering.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Do '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Optionally provide other information that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
