parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.16.x'
    inputs:
      versionSpec: 10.16.x

  - script: yarn install
    displayName: "Install Dependencies"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: yarn run compile
    displayName: "Compile Sources"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: yarn run pr-check
    displayName: 'Validate Extension/package.json'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: yarn run lint
    displayName: 'Run Linter'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: |
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
    displayName: 'Start xvfb'

  - script: yarn run pretest
    displayName: "Compile Test Sources"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: 'yarn run unitTests'
    displayName: 'Run unit tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'
    env:
      DISPLAY: :10

  - script: 'yarn run integrationTests'
    displayName: 'Run languageServer integration tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'
    env:
      DISPLAY: :10

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    continueOnError: true
