parameters:
  name: ''
  pool: ''

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.16.x'
    inputs:
      versionSpec: 10.16.x

  - script: yarn install
    displayName: "Install Dependencies"
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: yarn run generatePackageHashes
    displayName: "Generate hashes for runtime dependency packages"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: yarn run compile
    displayName: "Compile Sources"
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: yarn run pr-check
    displayName: 'Validate Extension/package.json'
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: yarn run lint
    displayName: 'Run Linter'
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: yarn run pretest
    displayName: "Compile Test Sources"
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: 'yarn run unitTests'
    displayName: 'Run unit tests'
    workingDirectory: '$(Build.SourcesDirectory)\Extension'

  - script: 'yarn run integrationTests'
    displayName: 'Run languageServer integration tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    continueOnError: true
