name: CI (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    uses: ./.github/workflows/job-compile-and-test.yml
    with:
      runner-env: ubuntu-22.04
      platform: linux