name: CI (Mac)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-for-mac:
    uses: ./.github/workflows/jobs-compile-and-test.yml
    with:
      runner-env: macos-12
      yarn-args: --network-timeout 100000