name: CI (Mac)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    uses: ./.github/workflows/job-compile-and-test.yml
    with:
      runner-env: macos-12
      platform: mac
      yarn-args: --network-timeout 100000