name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    uses: ./.github/workflows/job-compile-and-test.yml
    with:
      runner-env: windows-2022
      platform: windows
