name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target-ref:
        description: Branch, tag, or SHA to test
        required: true
        default: main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  job:
    uses: ./.github/workflows/job-compile-and-test.yml
    with:
      runner-env: windows-2025
      platform: windows
      checkout-ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target-ref || github.ref }}
