name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  uses: ./.github/workflows/jobs-compile-and-test.yml
  with:
    runner-env: windows-2022
