name: Enhancement Reopener
on:
  schedule:
    - cron: 0 11 * * * # Run at 11:00 AM UTC (3:00 AM PST, 4:00 AM PDT)
  workflow_dispatch:
   inputs:
     readonly:
       description: "readonly: Specify true or 1 to prevent changes from being commited to GitHub"
       default: false

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: Run Reopener
        uses: ./.github/actions/Reopener
        with:
          readonly: ${{ github.event.inputs.readonly }}
          alsoApplyToOpenIssues: true
          reopenComment: This feature request has received enough votes to be added to our backlog.
          labels: enhancement
          minimumVotes: 3
          ignoreLabels: debugger,internal,Feature Request
          milestoneId: 30
          milestoneName: Triage
          setMilestoneId: 28
          removeLabels: more votes needed
