name: External closer - debugger
on:
  schedule:
    - cron: 10 13 * * * # Run at 1:10 PM UTC (5:10 AM PST, 6:10 AM PDT)
  workflow_dispatch:
   inputs:
     readonly:
       description: "readonly: Specify true or 1 to prevent changes from being commited to GitHub"
       default: false

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: Stale Closer
        uses: ./.github/actions/StaleCloser
        with:
          readonly: ${{ github.event.inputs.readonly }}
          labels: external,debugger
          ignoreLabels: Language Service,internal
          closeDays: 0
          closeComment: "This issue has been closed because it is external or not applicable to the extension."
