name: Feature Request Closer
on:
  schedule:
    - cron: 40 11 * * * # Run at 11:40 AM UTC (3:40 AM PST, 4:40 AM PDT)
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: Stale Closer
        uses: ./.github/actions/StaleCloser
        with:
          labels: Feature Request
          ignoredLabels: debugger
          addLabels: more votes needed
          closeDays: 60
          maximumVotes: 1
          closeComment: "This feature request is being closed due to insufficient upvotes.  When at least 2 upvotes are received, this issue will be eligible for our backlog."
          milestoneName: Triage
          milestoneId: 30
