name: Feature Request Manager
on:
  schedule:
    - cron: 40 11 * * * # Run at 11:40 AM UTC (3:40 AM PST, 4:40 AM PDT)
  issues:
    types: [milestoned]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        if: github.event_name != 'issues' || contains(github.event.issue.labels.*.name, 'Feature Request')
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          path: ./actions
          ref: v35
      - name: Install Actions
        if: github.event_name != 'issues' || contains(github.event.issue.labels.*.name, 'Feature Request')
        run: npm install --production --prefix ./actions
      - name: Run Feature Request Manager
        if: github.event_name != 'issues' || contains(github.event.issue.labels.*.name, 'Feature Request')
        uses: ./actions/feature-request
        with:
          candidateMilestoneID: 30
          candidateMilestoneName: Triage
          backlogMilestoneID: 28
          featureRequestLabel: Feature Request
          upvotesRequired: 2
          numCommentsOverride: 20
          initComment: "This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it.\n\nHappy Coding!"
          warnComment: "This feature request has not yet received the 2 community upvotes it takes to make it to our backlog. 10 days to go.\n\nHappy Coding!"
          acceptComment: ":slightly_smiling_face: This feature request received a sufficient number of community upvotes and we moved it to our backlog.\n\nHappy Coding!"
          rejectComment: ":slightly_frowning_face: In the last 60 days, this feature request has received less than 2 community upvotes and we closed it. Still a big Thank You to you for taking the time to create this issue!\n\nHappy Coding!"
          warnDays: 10
          closeDays: 60
          milestoneDelaySeconds: 60