name: Compile and test Hornet extension

on:
  workflow_call:
    inputs:
      runner-env:
        required: true
        type: string
      platform:
        required: true
        type: string
      checkout-ref:
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.runner-env }}
    defaults:
      run:
        working-directory: Extension
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.checkout-ref }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: Extension/package-lock.json
      - name: Install public dependencies
        run: npm ci
      - name: Compile sources
        run: npm run compile
      - name: Run unit tests
        run: npm test
      - name: Package universal VSIX on this host
        run: npm run package
      - uses: actions/upload-artifact@v4
        with:
          name: hornet-${{ inputs.platform }}
          path: Extension/*.vsix
          if-no-files-found: error
