# Reuable workflow for compiling and testing extension.
name: Compile and test extension

on:
  workflow_call:
    inputs:
      runner-env:
        required: true
        type: string
      yarn-args:
        type: string


jobs:
  build:
    runs-on: ${{ inputs.runner-env }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install ${{ inputs.yarn-args }}
        working-directory: Extension

      - name: Compile Sources
        run: yarn run compile
        working-directory: Extension

      - name: Run Linter
        run: yarn run lint
        working-directory: Extension

      - name: Run unit tests
        run: yarn test
        working-directory: Extension

#      # NOTE : We can't run the test that require the native binary files
#      #        yet -- there will be an update soon that allows the tester to 
#      #        acquire them on-the-fly
#      - name: Run simple vscode unit tests
#        run: yarn test --scenario=SingleRootProject
#        working-directory: Extension

#      - name: Run languageServer integration tests
#        run: yarn run integrationTests
#        working-directory: Extension