name: Locker
on:
  schedule:
    - cron: 0 11 * * * # Run at 11 AM UTC (3 AM PST, 4 AM PDT)

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          path: ./actions
          ref: v35
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose: 45
          daysSinceUpdate: 3
          ignoredLabel: "*more votes needed"
