name: Question Closer
on:
  schedule:
    - cron: 20 11 * * * # Run at 11:20 AM UTC (3:20 AM PST, 4:20 AM PDT)
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: Stale Closer
        uses: ./.github/actions/StaleCloser
        with:
          labels: question
          ignoredLabels: debugger
          closeDays: 60
          closeComment: "This issue has been closed automatically because it's labeled as a 'question' and has not had recent activity."
          pingDays: 80
          pingComment: "Hey @${assignee}, this issue might need further attention.\n\n@${author}, you can help us out by closing this issue if the question has been answered."
