name: Question Closer
on:
  schedule:
    - cron: 20 11 * * * # Run at 11:20 AM UTC (3:20 AM PST, 4:20 AM PDT)

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          path: ./actions
          ref: v35
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Needs More Info Closer
        uses: ./actions/needs-more-info-closer
        with:
          label: question
          closeDays: 14
          closeComment: "This issue has been closed automatically because it's labeled as a 'question' and has not had recent activity.\n\nHappy Coding!"
          pingDays: 80
          pingComment: "Hey @${assignee}, this issue might need further attention.\n\n@${author}, you can help us out by closing this issue if the question has been answered."
